spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: root
    url: jdbc:postgresql://127.0.0.1:5432/appro

  flyway:
    enabled: true

  jpa:
    show-sql: true

app:
  destination:
    image:
    photo: