server:
  port: 3001

spring:
  profiles:
    active: dev

  jpa:
    open-in-view: false

feedback:
  email:
    to: guchithehasky@gmail.com
    from: guchithehasky@gmail.com
    api-key: eruk wpkt jxic qyon