server:
  port: ${SERVER_PORT}

spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${APPRO_DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    open-in-view: false

  flyway:
    enabled: true

springdoc:
  swagger-ui:
    path: /v1/appro-docs

feedback:
  email:
    to: ${HUSKY_EMAIL}
    from: ${HUSKY_EMAIL}
    api-key: ${HUSKY_EMAIL_API_KEY}