name: Deploy to Chexie

on: [ workflow_dispatch ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      EC2_IP: ${{ secrets.CHEXIE_IP }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    - name: Copy files to EC2
      run: |
        scp -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa -r . ubuntu@13.60.38.144:/home/ubuntu/appro

    - name: Deploy application on EC2
      run: |
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ubuntu@13.60.38.144 << 'EOF'
          cd /home/ubuntu/appro/client
          npm install
          npm run build
          
          cd /home/ubuntu/appro/appro-back
          mvn package
          java -jar target/appro-back.jar
        EOF
