name: Deploy to Amazon ECS

on: [ workflow_dispatch ]


env:
  AWS_REGION: eu-north-1
  ECR_REPOSITORY: https://github.com/Rooman/appro
#  ECS_SERVICE: MY_ECS_SERVICE
#  ECS_CLUSTER: MY_ECS_CLUSTER
#  ECS_TASK_DEFINITION: MY_ECS_TASK_DEFINITION
#  CONTAINER_NAME: MY_CONTAINER_NAME

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 16

      - name: Verify Java version
        run: java -version

      - name: Verify Node.js version
        run: node -v

      - name: Change to client directory
        run: cd client

      - name: Install dependencies
        run: npm install
        working-directory: client


