name: Deploy to Amazon ECS  # Назва pipeline

on:
  workflow_dispatch:  # Дозволяє ручний запуск workflow з вибором гілки
    inputs:
      branch:
        description: 'Branch to deploy'
        required: true
        default: 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'